main_routes:
    resource: "@DBiagiMainBundle/Controller/"
    type:     annotation

# Imports MainBundle routes
dbiagi_main_bundle:
    resource: "@DBiagiMainBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
lexik_monolog_browser:
    resource: "@LexikMonologBrowserBundle/Resources/config/routing.xml"
    prefix:   /log