security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_USER]
    firewalls:
        main:
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch_to }
            http_basic: ~
            pattern: ^/
            logout:       true
            anonymous:    true
            form_login:
                login_path: /login
            remember_me:
                secret: "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
            guard:
                authenticators:
                    - main.guard.authenticator

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/animapp, role: ROLE_USER }
        - { path: ^/log, role: ROLE_SUPER_ADMIN }