<?php

namespace App\Repository;

/**
 * AnimationPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimationPartRepository extends \Doctrine\ORM\EntityRepository
{
}
