<?php

namespace DBiagi\MainBundle\Repository;

/**
 * AnimationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest($limit){
        return $this->findBy([], ['updatedAt' => 'DESC'], $limit);
    }
}
