tcc_home:
    path:     /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/home.html.twig

tcc_projeto:
    path: /projeto
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/projeto.html.twig

tcc_galeria:
    path: /galeria
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/galeria.html.twig

tcc_registrar:
    path: /registrar
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/registro.html.twig

tcc_contato:
    path: /contato
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/contato.html.twig

tcc_termo:
    path: /termo
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/termo.html.twig

tcc_projeto:
    path: /projeto
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/projeto.html.twig

tcc_politica:
    path: /politica-de-privacidade-e-copyright
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/copyright.html.twig

tcc_email:
    path: /send
    defaults: { _controller: Index:send }
