main_home:
    path:     /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/home.html.twig

main_projeto:
    path: /projeto
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/projeto.html.twig

main_registrar:
    path: /registrar
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/registro.html.twig

main_termo:
    path: /termo
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/termo.html.twig

main_projeto:
    path: /projeto
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/projeto.html.twig

main_politica:
    path: /politica-de-privacidade-e-copyright
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Pages/copyright.html.twig

main_email:
    path: /send
    defaults: { _controller: Index:send }

dbiagi_main_routes:
    resource: "@DBiagiMainBundle/Controller"
    type: annotation