services:            
    main.event.user_registration:
        class: DBiagi\MainBundle\EventListener\UserRegistrationListener
        tags:
            - { name: kernel.event_subscriber }
    
    main.animation_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - DBiagi\MainBundle\Entity\Animation
            
    faker:
        class: Faker\Generator
        factory: [Faker\Factory, create]
        arguments: ["%locale%"]