services:
          
    app.form.registration:
        class: DBiagi\MainBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
            
    main.event.user_registration:
        class: DBiagi\MainBundle\EventListener\UserRegistrationListener
        tags:
            - { name: kernel.event_subscriber }
            
    faker:
        class: Faker\Generator
        factory: [Faker\Factory, create]
        arguments: ["%locale%"]