DBiagi\MainBundle\Entity\User:
    type: entity
    table: tcc_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
