vich_uploader:
    db_driver: orm
    mappings:
        upload_file:
            uri_prefix:         /upload
            upload_destination: '%kernel.root_dir%/../web/upload'
            namer: vich_uploader.namer_uniqid